package group;

import java.util.ArrayList;
import java.util.Random;

import character.Character;

/*
 * When a hero is killed they remain in the group
 */
public class HeroGroup extends Group {

	public HeroGroup(ArrayList<Character> characterList) {
		super(characterList);
		// TODO Auto-generated constructor stub
	}

	public HeroGroup(String char1, String char2, String char3) {
		super(char1, char2, char3);
		// TODO Auto-generated constructor stub
	}

	/*
	 * TODO: If group is dead and you call this method it will throw a divide by 0 Exception
	 * 
	 */
	@Override
	public void recieveAction(Action action){
		
		Character tempCharctr;
		//TODO: TEST
		switch(action.getTarget()){
		case ONE:
			tempCharctr = randomLivingGroupMember();
			tempCharctr.recieveAction(action);
			break;
		case TWO:
			//evenly distributes attackValue to each character
			action.setActionValue(action.getActionValue() /2);
			
			tempCharctr = randomLivingGroupMember();
			tempCharctr.recieveAction(action);
			
			tempCharctr = randomLivingGroupMember();
			tempCharctr.recieveAction(action);
			break;
		case ALL:
			int livingCount = 0;
			//evenly distributes attackValue to each group member
			for(Character character : group){
				if(character.isAlive())
					livingCount ++;
			}
			action.setActionValue(action.getActionValue() / livingCount);
			//Passes on Attack to every 
			for(Character character : group){
				character.recieveAction(action);
			}

		}
		
		
	}
	

	//Returns null if heal. (sends to action to other group)
	//Heal only works on living members of group
	@Override
	public Action determineAction(Action action) {
		switch(action.getHealOrHurt()){
		case HEAL:
			//Will send Action to appropriate Group Members
			//Need way to determine specific members to send to
			Character tempCharctr;
			switch(action.getTarget()){
			case ONE:
				tempCharctr = randomLivingGroupMember();
				tempCharctr.recieveAction(action);
				return null;
			case TWO:
				action.setActionValue(action.getActionValue() /2);
				
				tempCharctr = randomLivingGroupMember();
				tempCharctr.recieveAction(action);
				
				tempCharctr = randomLivingGroupMember();
				tempCharctr.recieveAction(action);
				return null;
			case ALL:
				int livingCount = 0;
				//evenly distributes attackValue to each group member
				for(Character character : group){
					if(character.isAlive())
						livingCount ++;
				}
				action.setActionValue(action.getActionValue() / livingCount);
				//Passes on Attack to every 
				for(Character character : group){
					character.recieveAction(action);
				}
				return null;
			}
		case DAMAGE:
			//Returns Action generated by group member
			return action;
		}
		return null;
		
	}

	@Override
	public boolean areAlive() {
		for(Character character : group){
			if(character.isAlive())//if 1 character is alive
				return true;
		}
		return false;
	}
	
	
}
